volumes:
  pcap:
  tls_keys:

services:
  client:
    image: riccardidario1/client-analysis:latest
    container_name: client
    volumes:
      - pcap:/app/pcap
      - tls_keys:/tls_keys
      - ./report:/app/output
      - ./start_client.py:/app/start_client.py
    stdin_open: true
    tty: true
    environment:
      - DEFAULT_GROUPS=mlkem512
      - SSLKEYLOGFILE=/tls_keys/tls-secrets.log
    entrypoint: ["/bin/sh", "-c", "sleep 2 && python3 /app/start_client.py && tail -f /dev/null"]
  
  wireshark:
    image: openquantumsafe/wireshark:latest
    container_name: pq_wireshark
    network_mode: "host"
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - pcap:/pcap
    stdin_open: true
    tty: true
    command: >
      tshark -i eth0 -f "tcp port 443 and host 192.168.1.8" -w /pcap/capture.pcap