- name: Installa Docker e librerie scientifiche su Amazon Linux 2023
  hosts: all
  become: true

  tasks:
    - name: Aggiorna la cache dnf
      dnf:
        update_cache: true

    - name: Installa pacchetti di base
      dnf:
        name:
          - python3-pip
          - ca-certificates
          - gnupg
          - rsync
        state: present

    - name: Installa Docker
      dnf:
        name: docker
        state: present

    - name: Abilita e avvia Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Aggiungi utente corrente al gruppo docker
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Installa librerie scientifiche Python via pip
      pip:
        name:
          - numpy
          - pandas
          - matplotlib
          - psutil

    - name: Crea cartella plugin Docker Compose se non esiste
      file:
        path: /usr/libexec/docker/cli-plugins
        state: directory
        mode: '0755'
        recurse: yes

    - name: Scarica docker-compose plugin ufficiale
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: '0755'