- name: Copia progetto WebAppPostQuantumClient su macchina EC2
  hosts: all
  become: true

  tasks:
    - name: Copia progetto WebAppPostQuantumClient in /home/ec2-user
      synchronize:
        src: ./WebAppPostQuantumClient/
        dest: /home/ec2-user/WebAppPostQuantumClient/
        recursive: yes
        delete: no
