- name: Installa Docker e librerie scientifiche su Ubuntu 22.04 (con Compose V2)
  hosts: all
  become: true

  tasks:
    - name: Aggiorna la cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installa pacchetti necessari per l'uso del repository Docker ufficiale
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Aggiunge la chiave GPG ufficiale di Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Aggiunge il repository Docker APT
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
        filename: docker

    - name: Aggiorna la cache APT dopo aggiunta repository
      apt:
        update_cache: yes

    - name: Installa Docker e Docker Compose V2
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Abilita e avvia il servizio Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Aggiunge l'utente ubuntu al gruppo docker
      user:
        name: ubuntu
        groups: docker
        append: true

    - name: Installa librerie scientifiche Python via pip
      apt:
        name: python3-pip
        state: present

    - name: Installa pacchetti scientifici Python
      pip:
        name:
          - numpy
          - pandas
          - matplotlib
          - psutil
          - flask
